name: BUILD_APK-DTC_BY_MANUAL

on:
  workflow_dispatch:
    inputs:
      x_branch:
        description: "指定Xray-core分支"
        required: true
        default: "main"
        type: choice
        options:
          - "main"
      x_commit_id:
        description: "指定Xray-core使用commit id版本"
        required: true
        default: "HEAD~0"
        type: string
      x_lib_repo:
        description: "指定AndroidLibXrayLite仓库"
        required: true
        default: "DTCproto"
        type: choice
        options:
          - "DTCproto"
          - "2dust"
      x_lib_branch:
        description: "指定AndroidLibXrayLite分支"
        required: true
        default: "main"
        type: string
      ng_repo:
        description: "指定v2rayNG仓库"
        required: true
        default: "DTCproto"
        type: choice
        options:
          - "DTCproto"
          - "2dust"
      ng_branch:
        description: "指定v2rayNG分支"
        required: true
        default: "hev-tun"
        type: choice
        options:
          - "master"
          - "hev-tun"
      ng_commit_id:
        description: "指定v2rayNG使用commit id版本"
        required: true
        default: "HEAD~0"
        type: string
      build_xray_elf:
        description: "build xray"
        default: false
        type: boolean
      release_archives:
        description: "enable release archives"
        default: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: java version
        run: |
          java --version

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@latest
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      #- name: Set up Gradle
      #  uses: gradle/actions/setup-gradle@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          log-accepted-android-sdk-licenses: false
          cmdline-tools-version: '12266719'
          packages: 'platforms;android-35 build-tools;35.0.0 platform-tools'

      - name: Install NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --channel=3 \
            --install "ndk;29.0.13113456"
          echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.13113456" >> "$GITHUB_ENV"
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/29.0.13113456" >> "$GITHUB_ENV"
          echo "use_ndk_version=29.0.13113456" >> "$GITHUB_ENV"

      - name: Install System Tools
        run: |
          sudo apt install tree -y

      - name: git clone v2rayNG
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          git clone -b ${{ inputs.ng_branch }} https://github.com/${{ inputs.ng_repo }}/v2rayNG.git
          cd ${{ github.workspace }}/build/v2rayNG
          git checkout --force --quiet ${{ inputs.ng_commit_id }}
          git submodule update --init --recursive

      - name: edit v2rayNG source code
        if: ${{ inputs.ng_branch != 'hev-tun' }}
        run: |
          cd ${{ github.workspace }}/build/v2rayNG/V2rayNG
          chmod 755 *
          sed -i 's/applicationId = "com.v2ray.ang"/applicationId = "com.xray.ang.dev"/' ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/build.gradle.kts

      - name: edit v2rayNG source code(HevTun)
        if: ${{ inputs.ng_branch == 'hev-tun' }}
        run: |
          cd ${{ github.workspace }}/build/v2rayNG/V2rayNG
          chmod 755 *
          sed -i 's/applicationId = "com.v2ray.ang"/applicationId = "com.xray.ang.hev.dev"/' ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/build.gradle.kts

      - name: add mapdns
        run: |
           sed -i '/appendLine("  udp: '\''udp'\''")/a\
            appendLine("mapdns:")\
            appendLine("  address: 198.18.0.2")\
            appendLine("  port: 53")\
            appendLine("  network: 240.0.0.0")\
            appendLine("  netmask: 240.0.0.0")\
            appendLine("  cache-size: 10000")' \
            ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/src/main/java/com/v2ray/ang/service/V2RayVpnService.kt
      - name: add v2rayNG ndk version
        run: |
          sed -i $'10i\\\n    ndkVersion = "${{ env.use_ndk_version }}"' ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/build.gradle.kts

      - name: import apk sign config
        run: |
          cp ${{ github.workspace }}/.github/workflows/dt.jks ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/dt.jks

      - name: git clone AndroidLibXrayLite
        run: |
          mkdir -p ${{ github.workspace }}/build
          cd ${{ github.workspace }}/build
          git clone -b ${{ inputs.x_lib_branch }} https://github.com/${{ inputs.x_lib_repo }}/AndroidLibXrayLite.git

      - name: use git remote repo xray
        run: |
          mkdir -p ${{ github.workspace }}/build/AndroidLibXrayLite/ActionsBuild
          cd ${{ github.workspace }}/build/AndroidLibXrayLite/ActionsBuild
          rm -rf Xray-core
          git clone -b ${{ inputs.x_branch }} https://github.com/XTLS/Xray-core.git
          cd ${{ github.workspace }}/build/AndroidLibXrayLite/ActionsBuild/Xray-core
          git checkout --force --quiet ${{ inputs.x_commit_id }}
          echo "x_short_version=$(git rev-parse --short HEAD)" >> "$GITHUB_ENV"

      - name: edit lib version
        run: |
          sed -i 's/var version/\/\/ var version/g' ${{ github.workspace }}/build/AndroidLibXrayLite/libv2ray_main.go
          echo ${{ env.x_short_version }} | xargs -I '{}' sed -i 's/fmt.Sprintf("Lib v%d, Xray-core v%s", version, v2core.Version())/fmt.Sprintf("(Lib)Xray-core v%s", v2core.Version()+"@{}")/g' ${{ github.workspace }}/build/AndroidLibXrayLite/libv2ray_main.go
          echo ${{ env.x_short_version }} | xargs -I '{}' sed -i 's/fmt.Sprintf("Lib v%d, Xray-core v%s", version, core.Version())/fmt.Sprintf("(Lib)Xray-core v%s", core.Version()+"@{}")/g' ${{ github.workspace }}/build/AndroidLibXrayLite/libv2ray_main.go

      - name: fix lib conflict
        run: |
          cp -rf ${{ github.workspace }}/ext/nouse.go ${{ github.workspace }}/build/AndroidLibXrayLite
          cd ${{ github.workspace }}/build/AndroidLibXrayLite
          go get google.golang.org/genproto@v0.0.0-20250422160041-2d3770c4ea7f
          go get google.golang.org/genproto/googleapis/rpc@v0.0.0-20250422160041-2d3770c4ea7f

      - name: go get specify xray
        run: |
          cd ${{ github.workspace }}/build/AndroidLibXrayLite
          go get github.com/xtls/xray-core@${{ env.x_short_version }}

      - name: Build xray exe
        if: ${{ inputs.build_xray_elf }}
        run: |
          cd ${{ github.workspace }}/build/AndroidLibXrayLite/ActionsBuild/Xray-core
          mkdir build_assets
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o build_assets/xray -trimpath -buildvcs=false -ldflags "-s -w -buildid=" ./main
          CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build -v -o build_assets/xray_arm64 -trimpath -buildvcs=false -ldflags "-s -w -buildid=" ./main
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -o build_assets/xray.exe -trimpath -buildvcs=false -ldflags "-s -w -buildid=" ./main

      - name: Build libv2ray aar
        run: |
          cd ${{ github.workspace }}/build/AndroidLibXrayLite
          gomobile init
          go mod tidy -v
          gomobile bind -v -androidapi 21 -trimpath -ldflags='-s -w -buildid=' ./
          mkdir -p ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/libs
          cp *.aar ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/libs/

      - name: Build Other libs
        if: ${{ inputs.ng_branch != 'hev-tun' }}
        run: |
          cd ${{ github.workspace }}/build/v2rayNG
          bash compile-tun2socks.sh
          tree ${{ github.workspace }}/build/v2rayNG/libs/
          cp -r ${{ github.workspace }}/build/v2rayNG/libs/* ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/libs/
          bash libhysteria2.sh
          tree ${{ github.workspace }}/build/v2rayNG/hysteria/libs/
          cp -r ${{ github.workspace }}/build/v2rayNG/hysteria/libs/* ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/libs/

      - name: Build Other libs(HevTun)
        if: ${{ inputs.ng_branch == 'hev-tun' }}
        run: |
          cd ${{ github.workspace }}/build/v2rayNG
          bash libhysteria2.sh
          tree ${{ github.workspace }}/build/v2rayNG/hysteria/libs/
          cp -r ${{ github.workspace }}/build/v2rayNG/hysteria/libs/* ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/libs/

      - name: Build APK
        run: |
          tree ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/libs/
          cd ${{ github.workspace }}/build/v2rayNG/V2rayNG
          ./gradlew assembleRelease -Pandroid.injected.signing.store.file=${{ github.workspace }}/build/v2rayNG/V2rayNG/app/dt.jks -Pandroid.injected.signing.store.password="dt@pwd" -Pandroid.injected.signing.key.alias="dt" -Pandroid.injected.signing.key.password="dt@pwd"

      - name: Upload xray exe
        if: ${{ inputs.build_xray_elf }}
        uses: actions/upload-artifact@v4
        with:
          name: bin-${{ env.x_short_version }}
          compression-level: 9
          path: |
            ${{ github.workspace }}/build/AndroidLibXrayLite/ActionsBuild/Xray-core/build_assets/*

      - name: Upload aar
        uses: actions/upload-artifact@v4
        with:
          name: aar-${{ env.x_short_version }}
          compression-level: 9
          path: |
            ${{ github.workspace }}/build/AndroidLibXrayLite/*.aar

      - name: Upload arm dev apk
        uses: actions/upload-artifact@v4
        with:
          name: apks_arm_v8a_dev-${{ env.x_short_version }}
          compression-level: 9
          path: |
            ${{ github.workspace }}/build/v2rayNG/V2rayNG/app/build/outputs/apk/**/*.apk
            !${{ github.workspace }}/**/*null*
            !${{ github.workspace }}/**/*x86*
            !${{ github.workspace }}/**/*riscv*
            !${{ github.workspace }}/**/*mips
