name: kiss

on:
  workflow_dispatch:
  push:
    branches: [ new ]
  pull_request:
    branches: [ new ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: Neamar/KISS
          ref: master
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
       
      - name: Fetch Pull Request Branch
        run: git fetch https://github.com/Neamar/KISS.git +refs/pull/2236/merge
      - name: Merge Commits
        run: |
          # Merge specific commits from the pull request
          git merge FETCH_HEAD
      - name: Fetch Pull Request Branch
        run: git fetch https://github.com/Neamar/KISS.git +refs/pull/2252/merge
      - name: Merge Commits
        run: |
          # Merge specific commits from the pull request
          git merge FETCH_HEAD
      - name: Fetch Pull Request Branch
        run: git fetch https://github.com/Neamar/KISS.git +refs/pull/2264/merge
      - name: Merge Commits
        run: |
          # Merge specific commits from the pull request
          git merge FETCH_HEAD
      
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --build-cache --parallel

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: KISS
          path: app/build/outputs/apk/release/*.apk

      - name: Archive reports for failed job
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '*/build/reports'
        if: ${{ failure() }}
