name: libre

on:
  workflow_dispatch:
  push:
    branches: [ new ]
  pull_request:
    branches: [ new ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          repository: libre-tube/LibreTube
          ref: master
          

      - name: ADD
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .  
      
   #   - name: Fetch Specific Commit
   #     run: git fetch https://github.com/akashs056/LibreTube.git 4003537f982d9531faa29107711ebdf1b9382b27

    #  - name: Merge Specific Commit
    #    run: |
    #     git merge FETCH_HEAD
    #  - name: Fetch Pull Request Branch
    #    run: git fetch https://github.com/libre-tube/LibreTube.git +refs/pull/5817/merge
    #  - name: Merge Commits
     #   run: |
      #    # Merge specific commits from the pull request
       #   git merge FETCH_HEAD
 #     - name: Fetch Pull Request Branch
   #     run: git fetch https://github.com/libre-tube/LibreTube.git +refs/pull/5796/merge
  #    - name: Merge Commits
    #    run: |
          # Merge specific commits from the pull request
   #       git merge FETCH_HEAD
    #  - name: Fetch Pull Request Branch
  #      run: git fetch https://github.com/libre-tube/LibreTube.git +refs/pull/5757/merge
 #     - name: Merge Commits
   #     run: |
          # Merge specific commits from the pull request
    #      git merge FETCH_HEAD
     # - name: Revert Commit
   #     run: git revert 0b059ccc12ab5a6df89c3c61f34680ad18db5471 --no-edit
            
        #  git revert -v -n 0b059cc --no-edit -X theirs
        #  sed -i '/import com\.github\.libretube\.ui\.extensions\.trySetTooltip/d' app/src/main/java/com/github/libretube/ui/views/CustomExoPlayerView.kt
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-overwrite-existing: true
          cache-disabled: true
      - name: cache
        uses: actions/cache@v6
        with:
         path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
           ~/.gradle/notifications
           ~/.gradle/configuration-cache
           **/.gradle/configuration-cache
           **/.gradle/caches
         key: ${{ runner.os }}-gradlelibret-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
         restore-keys: |
            ${{ runner.os }}-gradlelibret-
      

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --no-daemon --parallel --build-cache --configuration-cache -Pandroid.enableR8.fullMode=true -Dorg.gradle.workers.max=8 -Dorg.gradle.jvmargs="-Xmx4g -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m" -Pandroid.injected.build.abi=arm64-v8a -PtargetAbi=arm64-v8a -PABI_FILTERS=arm64-v8a -Pandroid.injected.testOnly=false -Pandroid.injected.resConfigs=en,en_PK,en-pk -x check $(./gradlew tasks --all --quiet 2>/dev/null | awk '/lint|analyze|test|Test/{gsub(/.*:/,""); print "-x " $1}' | tr '\n' ' ')


    #  - name: Upload APK
   #     uses: actions/upload-artifact@v3
   #     with:
    #      name: Libre
     #     path: app/build/outputs/apk/release/app-arm64-v8a*.apk
      
      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: lib
          name: lib
          prerelease: false
          draft: false
          files: "**/*.apk"
