name: libre

on:
  workflow_dispatch:
  push:
    branches: [ new ]
  pull_request:
    branches: [ new ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          repository: libre-tube/LibreTube
          ref: master
          fetch-depth: 0

      - name: ADD
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .  
      
   #   - name: Fetch Specific Commit
   #     run: git fetch https://github.com/akashs056/LibreTube.git 4003537f982d9531faa29107711ebdf1b9382b27

    #  - name: Merge Specific Commit
    #    run: |
    #     git merge FETCH_HEAD
    #  - name: Fetch Pull Request Branch
     #   run: git fetch https://github.com/libre-tube/LibreTube.git +refs/pull/5607/merge
   #   - name: Merge Commits
      #  run: |
          # Merge specific commits from the pull request
     #    git merge FETCH_HEAD
   #   - name: Fetch Pull Request Branch
  #      run: git fetch https://github.com/libre-tube/LibreTube.git +refs/pull/5645/merge
   #   - name: Merge Commits
   #     run: |
          # Merge specific commits from the pull request
     #     git merge FETCH_HEAD
 #     - name: Fetch Pull Request Branch
  #      run: git fetch https://github.com/libre-tube/LibreTube.git +refs/pull/5646/merge
  #    - name: Merge Commits
   #     run: |
          # Merge specific commits from the pull request
    #      git merge FETCH_HEAD
     # - name: Revert Commit
   #     run: git revert 0b059ccc12ab5a6df89c3c61f34680ad18db5471 --no-edit
      - name: Revert Commit
        run: |
          git revert -v -n -m 1 ce8ed66 --no-edit -X ours
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --build-cache --parallel

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Libre
          path: app/build/outputs/apk/release/app-arm64-v8a*.apk

      - name: Archive reports for failed job
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '*/build/reports'
        if: ${{ failure() }}
