name: MPVRx

permissions:
  contents: write
  pages: write
  id-token: write

on:
  workflow_dispatch: # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      commit_count: ${{ steps.set_commit.outputs.commit_count }}
      build_time: ${{ steps.set_commit.outputs.build_time }}
      arm64-v8a_size: ${{ steps.set_commit.outputs.arm64-v8a_size }}
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: Riteshp2001/mpvRx
          ref: master
          fetch-depth: 0
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
           swap-size-gb: 10
      - name: Boostrap Gradle Memory
        shell: bash
        run: |
         wget https://raw.githubusercontent.com/PaulWoitaschek/Voice/refs/heads/main/scripts/gradle_bootstrap.sh
         chmod +x gradle_bootstrap.sh
         bash gradle_bootstrap.sh
      - name: Setup JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'adopt'
          java-version: 17
          cache: gradle
      - name: Enable Gradle caching
        run: |
          echo "" >> ${{ github.workspace }}/gradle.properties
          echo "org.gradle.caching=true" >> ${{ github.workspace }}/gradle.properties
          echo "org.gradle.configuration-cache=true" >> ${{ github.workspace }}/gradle.properties
          echo "org.gradle.configureondemand=true" >> /home/runner/work/Apps/Apps/gradle.properties
          echo "org.gradle.configuration-cache.encryption=false" >> ${{ github.workspace }}/gradle.properties
          echo "org.gradle.unsafe.configuration-cache-problems=warn" >> ${{ github.workspace }}/gradle.properties
          echo "org.gradle.daemon=true" >> ${{ github.workspace }}/gradle.properties
          echo "org.gradle.parallel=true" >> ${{ github.workspace }}/gradle.propertie
          sed -i -e '$a\' ${{ github.workspace }}/gradle.properties
          echo "android.lint.abortOnError=false" >> ${{ github.workspace }}/gradle.properties
          echo "android.lint.checkReleaseBuilds=false" >> ${{ github.workspace }}/gradle.properties

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
         cache-overwrite-existing: true
         cache-disabled: true
      - name: cache
        uses: actions/cache@v6
        with:
         path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
           ~/.gradle/notifications
           ~/.gradle/configuration-cache
           **/.gradle/configuration-cache
           **/.gradle/caches
         key: ${{ runner.os }}-gradlempvrx-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/.gradle/configuration-cache') }}
         restore-keys: |
            ${{ runner.os }}-gradlempvrx-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: |
         sed -i -e 's/isMinifyEnabled[[:space:]]*=[[:space:]]*true/isMinifyEnabled = false/g' -e 's/isShrinkResources[[:space:]]*=[[:space:]]*true/isShrinkResources = false/g' app/build.gradle.kts
         ./gradlew assembleStandardRelease --no-daemon --parallel --build-cache --configuration-cache -Pandroid.enableR8.fullMode=false -Dorg.gradle.workers.max=8 -Dorg.gradle.jvmargs="-Xmx4g -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m" -Pandroid.injected.build.abi=arm64-v8a -PtargetAbi=arm64-v8a -PABI_FILTERS=arm64-v8a -Pandroid.injected.testOnly=false -Pandroid.injected.resConfigs=en,en_PK,en-pk -x check $(./gradlew tasks --all --quiet 2>/dev/null | awk '/lint|analyze|test|Test/{gsub(/.*:/,""); print "-x " $1}' | tr '\n' ' ')



      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: mpvRx
          name: mpvRx
          prerelease: false
          draft: false
          files: "**/*.apk"
      
