name: Revert Commit and Build

on:
  workflow_dispatch:

jobs:
  revert_commit_and_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Revert commit
        run: git revert 0b059ccc12ab5a6df89c3c61f34680ad18db5471

      - name: Resolve conflicts if any
        run: git diff --check && git diff-index --quiet HEAD --

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease --build-cache --parallel

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: Libre
          path: app/build/outputs/apk/release/app-arm64-v8a*.apk

      - name: Archive reports for failed job
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: '*/build/reports'
        if: ${{ failure() }}
