name: starlight

on:
  workflow_dispatch:
  push:
    branches: [ new ]
  pull_request:
    branches: [ new ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: TBog/TBLauncher
          ref: refactor
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
 
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
   #   - name: Filter
    #    run: sed -i '/^ *signingConfigs {/,/^ *}/d' app/build.gradle
      - name: Build with Gradle
        run: ./gradlew assembleRelease --build-cache --parallel --warning-mode none

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: starlight
          path: app/build/**/*.apk

      - name: Archive reports for failed job
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: '*/build/reports'
        if: ${{ failure() }}
