# Generates and uploads a release version when a new tag is pushed
name: URL checker

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v7
        with:
          repository: TrianguloY/UrlChecker
          ref: master
      - name: Enable Gradle caching
        run: |
         cat >> ${{ github.workspace }}/gradle.properties << EOF
         org.gradle.caching=true
         org.gradle.configuration-cache=true
         org.gradle.configuration-cache.problems=warn
         org.gradle.configureondemand=true
         org.gradle.parallel=true
         org.gradle.daemon=true
         EOF

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Boostrap Gradle Memory
        shell: bash
        run: |
         wget https://raw.githubusercontent.com/PaulWoitaschek/Voice/refs/heads/main/scripts/gradle_bootstrap.sh
         chmod +x gradle_bootstrap.sh
         bash gradle_bootstrap.sh
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-overwrite-existing: true
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      
      - name: Build & assemble
        run: ./gradlew build assembleRelease --no-daemon --parallel --build-cache --configuration-cache --info --stacktrace -Pandroid.enableR8.fullMode=true -Dorg.gradle.workers.max=8 -Dorg.gradle.jvmargs="-Xmx4g -XX:+UseG1GC -XX:MaxMetaspaceSize=1024m -XX:ReservedCodeCacheSize=256m" -Pandroid.injected.build.abi=arm64-v8a -PtargetAbi=arm64-v8a -PABI_FILTERS=arm64-v8a -Pandroid.injected.testOnly=false -Pandroid.injected.resConfigs=en,en_PK,en-pk -x check $(./gradlew tasks --all --quiet 2>/dev/null | awk '/lint|analyze|test|Test/{gsub(/.*:/,""); print "-x " $1}' | tr '\n' ' ')
      - name: Upload logs and Configuration Cache report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gradle-debug-${{ github.run_id }}
          path: |
            **/build/reports/configuration-cache/*.html
            **/build/reports/configuration-cache/**
          if-no-files-found: ignore
          retention-days: 5
      - name: Publish release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: url
          name: url
          prerelease: false
          draft: false
          files: "**/*.apk"
