name: Build v2

on:
  workflow_dispatch:
    inputs:
      XRAY_CORE_VERSION:
        description: 'Xray core version or commit hash'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
          repository: 2dust/v2rayNG
          ref: 3de3070

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Create empty go.sum if it does not exist
      run: |
        if [ ! -f go.sum ]; then
          touch go.sum
        fi
    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        echo "$(go env GOPATH)/bin" >> $GITHUB_PATH


    - name: Setup Android environment
      uses: android-actions/setup-android@v3


    - name: Download libv2ray.aar
      run: |
        mkdir -p ${{ github.workspace }}/V2rayNG/app/libs/
        curl -L -o ${{ github.workspace }}/V2rayNG/app/libs/libv2ray.aar https://github.com/2dust/AndroidLibXrayLite/releases/latest/download/libv2ray.aar
    - name: Cache Gradle dependencies
      id: cache-gradle
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        chmod 755 gradlew
        ./gradlew assembleRelease
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.7.0
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/*.apk
          tag: v2
          overwrite: true
          file_glob: true
