name: Build v2hev
       
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        repository: DTCproto/v2rayNG
        ref: hev-tun
        submodules: 'recursive'
        fetch-depth: '0'
    - name: Prepare build dir
      run: |
        mkdir ${{ github.workspace }}/build
    
    - name: Fetch AndroidLibXrayLite
      run: |
        cd ${{ github.workspace }}/build
        git clone --depth=1 -b main https://github.com/2dust/AndroidLibXrayLite.git
        cd AndroidLibXrayLite
        git submodule update --init
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      with:
        log-accepted-android-sdk-licenses: false
        cmdline-tools-version: '12266719'
        packages: 'platforms;android-35 build-tools;35.0.0 platform-tools'

    - name: Install NDK
      run: |
        echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
          --channel=3 \
          --install "ndk;29.0.13113456"
        echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.13113456" >> $GITHUB_ENV
        sed -i '10i\
        \
            ndkVersion = "29.0.13113456"' ${{ github.workspace }}/V2rayNG/app/build.gradle.kts
 
    - name: Restore cached libv2ray
      id: cache-libv2ray-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/build/AndroidLibXrayLite/
        key: libv2ray-${{ runner.os }}-${{ hashFiles('/build/AndroidLibXrayLite/.git/refs/heads/main') }}

    - name: Setup Golang
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true
        cache-dependency-path: ${{ github.workspace }}/build/AndroidLibXrayLite/go.sum
    
    - name: Install gomobile
      run: |
        go install golang.org/x/mobile/cmd/gomobile@latest
        export PATH=$PATH:~/go/bin
    - name: Build libv2ray
      if: steps.cache-libv2ray-restore.outputs.cache-hit != 'true'
      run: |
        cd ${{ github.workspace }}/build/AndroidLibXrayLite
        go get github.com/xtls/xray-core@main || true
        gomobile init
        go mod tidy
        gomobile bind -v -androidapi 21 -trimpath -ldflags='-s -w -buildid=' ./
   #   env:
   #     ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
    - name: Save libv2ray
      if: steps.cache-libv2ray-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/build/AndroidLibXrayLite/
        key: libv2ray-${{ runner.os }}-${{ hashFiles('/build/AndroidLibXrayLite/.git/refs/heads/main') }}
    - name: Prepare build dir
      run: |
        mkdir ${{ github.workspace }}/V2rayNG/app/libs/
    - name: Copy libv2ray
      run: |
        cp -r ${{ github.workspace }}/build/AndroidLibXrayLite/*.aar ${{ github.workspace }}/V2rayNG/app/libs/

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
   
    - name: Restore cached libhysteria2
      id: cache-libhysteria2-restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ github.workspace }}/hysteria/libs
        key: libhysteria2-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hysteria/HEAD') }}-${{ hashFiles('libhysteria2.sh') }}
        
    - name: Build libhysteria2
      if: steps.cache-libhysteria2-restore.outputs.cache-hit != 'true'
      run: |
        bash libhysteria2.sh

    - name: Save libhysteria2
      if: steps.cache-libhysteria2-restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ github.workspace }}/hysteria/libs
        key: libhysteria2-${{ runner.os }}-${{ env.NDK_HOME }}-${{ hashFiles('.git/modules/hysteria/HEAD') }}-${{ hashFiles('libhysteria2.sh') }}

    - name: Copy libhysteria2
      run: |
        cp -r ${{ github.workspace }}/hysteria/libs ${{ github.workspace }}/V2rayNG/app

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
          
    - name: Build APK
      run: |
        cd ${{ github.workspace }}/V2rayNG
        echo "sdk.dir=${ANDROID_HOME}" > local.properties
        chmod 755 gradlew
        ./gradlew assembleRelease --build-cache
    #  env:
    #    ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
        
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@2.7.0
      with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/*playstore*/release/*.apk
          tag: v2hev
          overwrite: true
          file_glob: true
