name: Build v2 with Merged PRs

on:
  workflow_dispatch:
    inputs:
      XRAY_CORE_VERSION:
        description: 'Xray core version or commit hash'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
            repository: 2dust/v2rayNG
            ref: master

      - name: List Pull Requests
        id: list_prs
        uses: peter-evans/pull-request-list@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          search: 'is:open is:pr base:master'  # Adjust if targeting a different branch

      - name: Pull and Merge Pull Requests
        if: steps.list_prs.outputs.prs != '[]'
        run: |
          echo "Merging pull requests..."
          for pr in $(echo "${{ steps.list_prs.outputs.prs }}" | jq -r '.[] | .number'); do
            git fetch origin pull/$pr/head:pr-$pr
            git merge pr-$pr --no-ff --no-edit
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Create empty go.sum if it does not exist
        run: |
          if [ ! -f go.sum ]; then
            touch go.sum
          fi

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.4'
      
      - name: Install gomobile
        run: |
          go install golang.org/x/mobile/cmd/gomobile@v0.0.0-20240806205939-81131f6468ab
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Setup Android environment
        uses: android-actions/setup-android@v3

      - name: Download libv2ray.aar
        run: |
          mkdir -p ${{ github.workspace }}/V2rayNG/app/libs/
          curl -L -o ${{ github.workspace }}/V2rayNG/app/libs/libv2ray.aar https://github.com/2dust/AndroidLibXrayLite/releases/latest/download/libv2ray.aar

      - name: Cache Gradle dependencies
        id: cache-gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build APK
        run: |
          cd ${{ github.workspace }}/V2rayNG
          chmod 755 gradlew
          ./gradlew assembleRelease

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.7.0
        with:
            repo_token: ${{ secrets.GITHUB_TOKEN }}
            file: ${{ github.workspace }}/V2rayNG/app/build/outputs/apk/release/*.apk
            tag: v2
            overwrite: true
            file_glob: true
