name: xiv2

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # -------------------------------
      # Checkout xivpn repository
      # -------------------------------
      - name: Checkout xivpn
        uses: actions/checkout@v4
        with:
          submodules: true
          repository: Exclude0122/xivpn
          ref: master
      - name: del
        run: |
          bash -c 'inside=0; brace_count=0; while IFS= read -r line; do
          if [[ "$line" =~ signingConfigs[[:space:]]*{ ]]; then inside=1; brace_count=1; echo "// $line"; continue; fi
          if (( inside == 1 )); then
           open=$(grep -o "{" <<< "$line" | wc -l)
           close=$(grep -o "}" <<< "$line" | wc -l)
           brace_count=$(( brace_count + open - close ))
           echo "// $line"
           if (( brace_count == 0 )); then inside=0; fi
           continue
          fi
          if [[ "$line" =~ signingConfig[[:space:]]+signingConfigs\.[a-zA-Z0-9_]+ ]]; then
           echo "// $line"
          else
          echo "$line"
          fi
          done < app/build.gradle > app/build.gradle.tmp && mv app/build.gradle.tmp app/build.gradle'
      - name: MTU
        run: |
            sed -i \
            -e 's/inbound\.port = [0-9]\+/inbound.port = 0/' \
            -e '/inbound\.listen = "127\.0\.0\.1";/d' \
            -e 's/inbound\.settings\.put("MTU",[[:space:]]*[0-9]\+)/inbound.settings.put("MTU", 8500)/' \
            -e '/inbound\.protocol = "tun";/a\            inbound.tag = "tun";' \
            app/src/main/java/cn/gov/xivpn2/service/XiVPNService.java

            sed -i \
            '/public class Inbound {/a\    public String tag;' \
            app/src/main/java/cn/gov/xivpn2/xrayconfig/Inbound.java
          # Remove signingConfigs block (including nested braces) and comment signingConfig lines
          #perl -0777 -pe 's/signingConfigs\s*{.*?}\n//gs' app/build.gradle | sed 's/^\s*signingConfig signingConfigs\.[a-zA-Z0-9_]\+/\/\/ &/' > app/build.gradle.tmp && mv app/build.gradle.tmp app/build.gradle
          #awk '/signingConfigs[[:space:]]*{/ {inside=1} inside {print "// " $0} inside && /}$/ {inside=0; next} !inside {print}' app/build.gradle | sed 's/^\s*signingConfig signingConfigs\.[a-zA-Z0-9_]\+/\/\/ &/' > app/build.gradle.tmp && mv app/build.gradle.tmp app/build.gradle
      # -------------------------------
      # Setup Java
      # -------------------------------
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.0-rc.3'
          check-latest: true
          cache-dependency-path: "libxivpn/*.sum"
      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 10
      - name: Boostrap Gradle Memory
        shell: bash
        run: |
         wget https://raw.githubusercontent.com/PaulWoitaschek/Voice/refs/heads/main/scripts/gradle_bootstrap.sh
         chmod +x gradle_bootstrap.sh
         bash gradle_bootstrap.sh
      - name: build.sh
        run: |
         cd libxivpn
         wget https://raw.githubusercontent.com/t-e-s-tweb/v-rules/refs/heads/main/build.sh -N
         chmod +x build.sh
         cd ..
      - name: optimization
        run: |
          wget https://raw.githubusercontent.com/t-e-s-tweb/v-rules/refs/heads/main/patch.sh
          chmod +x patch.sh
          ./patch.sh
          go env
      # -------------------------------
      # Setup Android NDK
      # -------------------------------
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          add-to-path: false
          ndk-version: r27
          local-cache: true
      # -------------------------------
      # Update xray-core to latest main and compare SHA
      # -------------------------------
      - name: Update xray-core and compare SHA
        run: |
          cd libxivpn

          # XIVPN commit
          XIVPN_SHA=$(git rev-parse HEAD)
          echo "xivpn commit: $XIVPN_SHA"

          # Latest xray-core main SHA on GitHub
          XRAY_REMOTE_SHA=$(git ls-remote https://github.com/xtls/xray-core.git refs/heads/main | cut -f1)
          echo "Latest xray-core main commit on GitHub: $XRAY_REMOTE_SHA"

          # Update Go module to latest xray-core main
          go get github.com/xtls/xray-core@main
          go mod tidy

          # Extract pseudo-version SHA Go will actually use
          XRAY_LOCAL_PSEUDO=$(go list -m -json github.com/xtls/xray-core | jq -r '.Version')
          XRAY_LOCAL_SHA=$(echo $XRAY_LOCAL_PSEUDO | awk -F'-' '{print $3}')
          echo "xray-core pseudo-version SHA used by libxivpn: $XRAY_LOCAL_SHA"

          # Compare SHAs
          if [ "$XRAY_LOCAL_SHA" = "$XRAY_REMOTE_SHA" ]; then
            echo "✅ xray-core is up to date"
          else
            echo "⚠️ xray-core used by libxivpn is not the latest main commit"
          fi
      - name: patch xmux
        run: |
         MODCACHE=$(go env GOMODCACHE)
         MOD_PATH="$MODCACHE/github.com/xtls/xray-core"
         cd "$MOD_PATH"
         wget https://raw.githubusercontent.com/t-e-s-tweb/v-rules/refs/heads/main/xmuxpatch.sh
         bash xmuxpatch.sh
         cd ..
         grep "go build" libxivpn/build.sh

      # -------------------------------
      # Build Android .so libraries
      # -------------------------------
      - name: Build Android libraries
        working-directory: ./libxivpn
        env:
          NDK: ${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64
        run: |
          ./build.sh arm64
          go env
          mkdir -p ../app/src/main/jniLibs/arm64-v8a
          #  mkdir -p ../app/src/main/jniLibs/x86_64
          #  mkdir -p ../app/src/main/jniLibs/armeabi-v7a
          #  cp libxivpn_x86_64.so ../app/src/main/jniLibs/x86_64/libxivpn.so
          cp libxivpn_arm64.so ../app/src/main/jniLibs/arm64-v8a/libxivpn.so
          # cp libxivpn_armv7a.so ../app/src/main/jniLibs/armeabi-v7a/libxivpn.so

      # -------------------------------
      # Setup Android SDK
      # -------------------------------
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # -------------------------------
      # Build APKs without signing
      # -------------------------------
      - name: Build APKs
        run: |
          ./gradlew assembleRelease $(./gradlew tasks --all 2>/dev/null | awk '/lint/{gsub(/.*:/,""); print "-x " $1}' | tr '\n' ' ')

        
      # -------------------------------
      # Show SHAs and APK outputs
      # -------------------------------
      - name: Show SHAs and APK paths
        run: |
          echo "xivpn commit: $(git rev-parse HEAD)"
          XRAY_SHA=$(go list -m -json github.com/xtls/xray-core | jq -r '.Version')
          echo "xray-core pseudo-version: $XRAY_SHA"
          echo "APK outputs:"
          find ./app/build/outputs/apk -type f -name "*.apk"

      # -------------------------------
      # Release step (GitHub release)
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@2.7.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/app/build/outputs/apk/*/release/*.apk
          tag: xiv2
          overwrite: true
          file_glob: true
